export const BEUTY_CATEGORY_START_INDEX = 0
export const BEUTY_CATEGORY_END_INDEX = 2

export const FASHION_CATEGORY_START_INDEX = 2
export const FASHION_CATEGORY_END_INDEX = 6

export const HOBBY_CATEGORY_START_INDEX = 6
export const HOBBY_CATEGORY_END_INDEX = 10
